# Generated by Django 5.1.6 on 2025-02-14 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_alter_group_academic_year'),
        ('subjects', '0005_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='students_images')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11')], default='grade_9', max_length=100)),
                ('address', models.TextField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254, unique=100)),
                ('parent_phone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group')),
                ('subjects', models.ManyToManyField(related_name='students', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
