# Generated by Django 5.1.6 on 2025-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
