# Generated by Django 5.1.6 on 2025-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='relationship',
            field=models.CharField(default='Father', max_length=100),
            preserve_default=False,
        ),
    ]
