# Generated by Django 5.1.6 on 2025-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default='2025-02-15'),
            preserve_default=False,
        ),
    ]
