# Generated by Django 5.1.6 on 2025-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joined_date',
            field=models.DateField(default='2025-02-13'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time '), ('contract', 'Contract')], default='full_time', max_length=100),
        ),
    ]
