# Generated by Django 5.1.6 on 2025-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_status'),
        ('teachers', '0003_teacher_joined_date_alter_teacher_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='teachers', to='subjects.subject'),
        ),
    ]
