# Generated by Django 5.1.6 on 2025-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_prerequisites'),
        ('teachers', '0004_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='subjects.subject'),
        ),
    ]
