# Generated by Django 5.1.6 on 2025-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(default='2025-02-15', max_length=100),
            preserve_default=False,
        ),
    ]
