# Generated by Django 5.1.6 on 2025-02-08 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.PositiveIntegerField()),
                ('grade_level', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('max_students', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('slug', models.SlugField(unique=100)),
                ('class_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='teachers.teacher')),
                ('subjects', models.ManyToManyField(related_name='groups', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
