# Generated by Django 5.1.6 on 2025-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_status'),
        ('subjects', '0005_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='groups', to='subjects.subject'),
        ),
    ]
