# Generated by Django 5.1.6 on 2025-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade_level',
            field=models.CharField(choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11')], default='grade_9', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(choices=[('morning_session', 'Morning Session'), ('afternoon_session', 'Afternoon Session'), ('evening_session', 'Evening Session')], default='morning_session', max_length=100),
        ),
    ]
