# Generated by Django 5.1.6 on 2025-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_grade_level_alter_group_schedule'),
        ('subjects', '0005_alter_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='subjects.subject'),
        ),
    ]
