# Generated by Django 5.1.6 on 2025-02-08 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('credit_hours', models.PositiveIntegerField()),
                ('grade_level', models.CharField(max_length=100)),
                ('prerequisites', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
