# Generated by Django 5.1.6 on 2025-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(choices=[('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11')], default='grade_9', max_length=100),
        ),
    ]
