# Generated by Django 5.1.6 on 2025-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='levels',
            field=models.CharField(choices=[('advanced', 'Advanced Level'), ('intermediate', 'Intermediate Level'), ('beginner', 'Beginner Level')], default='beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(choices=[('basic_mathematics', 'Basic Mathematics'), ('introduction_to_physics', 'Introduction to Physics'), ('basic_chemistry', 'Basic Chemistry'), ('english_language', 'English Language')], default='english_language', max_length=100),
        ),
    ]
